version: '3'
services:

  fsi-server:
    image: ${FSI_SERVER_IMAGE}:${FSI_SERVER_IMAGE_TAG}
    restart: always
    container_name: fsi-server
    environment:
      - SOLR_SERVER_URI=${SOLR_SERVER_URI}
      - LOG_FSI_LEVEL=${LOG_FSI_LEVEL}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ${FSI_CONFIG_PATH}:/srv/fsi/mounts/config
      - ${ASSET_PATH}:/srv/fsi/mounts/assets
      - ${OVERLAY_PATH}:/srv/fsi/mounts/overlay
      - ${STORAGE_PATH}:/srv/fsi/mounts/storage
      - ${LOG_PATH}/fsi:/srv/fsi/mounts/catalina/logs
    depends_on:
      - solr-server
    userns_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"

  solr-server:
    image: solr:6-alpine
    restart: always
    container_name: solr
    volumes:
      - ${SOLR_PATH}:/opt/solr/server/solr/fsi-server
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"

  nginx:
    build: container/nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${NGINX_CONFIG_PATH}:/etc/nginx
      - ${LOG_PATH}/nginx:/var/log/nginx
#      - /etc/letsencrypt/live:/etc/letsencrypt/live
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
