version: '3'
services:

  fsi-server:
    image: neptunelabs/fsi-server:${FSI_VERSION}
    restart: always
    container_name: fsi-server
    environment:
      - SOLR_SERVER_URI=http://solr-server:8983/solr/
      - LOG_FSI_LEVEL=${LOG_LEVEL}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./fsi-data:/srv/fsi/mounts
      - ${FSI_CONFIG_PATH}:/srv/fsi/mounts/config
      - ${ASSET_PATH}:/srv/fsi/mounts/assets
      - ${STORAGE_PATH}:/srv/fsi/mounts/storage
    depends_on:
      - solr-server
    userns_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"

  solr-server:
    image: solr:6-alpine
    restart: always
    container_name: solr
    volumes:
      - ./fsi-data/solr-core/fsi-server:/opt/solr/server/solr/fsi-server
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"

  nginx:
    image: nginx:${NGINX}
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/nginx:/etc/nginx:ro
      # - /var/log/nginx:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
